name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # You need to create a personal access token with repo, read:user, read:org scopes
          # and save it as a repository secret with the name METRICS_TOKEN
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: fsylmxx
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
